### ISSUE TITLE
Have you tried Yarn 2 (Berry) yet?

### ISSUE THREAD

**Issue by will-stone** [sindresorhus/ama#602] opened 2020-01-29 18:07 UTC
If so, what do you think?

**Comment by sindresorhus** [comment] 2020-02-07 07:49
No, and I don't think I will. I feel like they're trying to solve problems I simply never had. They're also breaking large parts of the ecosystem, which causes pain for me as a package author and users of my packages. They don't always release the problem is Yarn and blame me for the breakage. And IMHO, Berry was released way too early (they knew it broke large parts of the ecosystem) and it should have been released as a new project. It's completely different. That's just my personal opinions though.

**Closed by sindresorhus** 2020-02-07 07:49 UTC

**Comment by will-stone** [comment] 2020-02-07 08:45
Thanks, you have confirmed most of my own concerns. NPM's Tink looks like it'll be similar to Berry so I suppose we'll have to wait and see how that plays out; it may be that we'll have no choice but to support these PnP-esque environments. For now, my team and I have decided to stick with Yarn v1.
