### ISSUE TITLE
What are your thoughts on JS Standard ? 

### ISSUE THREAD

**Issue by gaboesquivel** [sindresorhus/ama#245] opened 2015-10-01 16:53 UTC
Hi Sindre, I think Feross has [made a point on javascript standards](http://standardjs.com/)
NPM uses it [npm/package.json#L187](https://github.com/npm/npm/blob/master/package.json#L187)
What do you think about it?

**Comment by sindresorhus** [comment] 2015-10-01 17:01
Duplicate of https://github.com/sindresorhus/ama/issues/96.

**Closed by sindresorhus** 2015-10-01 17:01 UTC
