### ISSUE TITLE
Which coding style do you use for your node modules?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/ama#83] opened 2015-07-03 06:22 UTC
Having contributed on some of your modules, I know that you use a stringent style guide. Is it a custom one? Or is it a subset of  a style guide that is out there? A super-set, perhaps?

**Comment by sindresorhus** [comment] 2015-07-04 10:40
Duplicate of #47.

**Closed by sindresorhus** 2015-07-04 10:40 UTC
