### ISSUE TITLE
Thoughts on extremely tiny modules?

### ISSUE THREAD

**Issue by skippednote** [sindresorhus/ama#147] opened 2015-07-12 15:26 UTC
This was recently tweeted https://twitter.com/felixge/status/619098296188039168
What are your thoughts on this?

Even I was going to create a group of similar modules but it seemed overkill has it was just a method call from the standard library.

**Comment by sindresorhus** [comment] 2015-07-12 15:32
Duplicate of https://github.com/sindresorhus/ama/issues/10

**Closed by sindresorhus** 2015-07-12 15:32 UTC
