### ISSUE TITLE
What's your typical day look like?

### ISSUE THREAD

**Issue by reneruiz** [sindresorhus/ama#432] opened 2016-11-17 22:43 UTC
Hey sindresorhus,

I use so many of your tools and appreciate all your contributions to open-source. I find myself in awe at how you're able to accomplish so much.

What's a standard day look like for you? What time do you wake up? How late do you usually work until? You must manage your time exceptionally well.

**Comment by sindresorhus** [comment] 2019-06-16 12:34
Duplicate of #167

**Closed by sindresorhus** 2019-06-16 12:34 UTC
