### ISSUE TITLE
What do you think of the npm left-pad chaos?

### ISSUE THREAD

**Issue by amitmerchant1990** [sindresorhus/ama#370] opened 2016-03-25 05:41 UTC
Some days ago, I came across this article.

http://www.theregister.co.uk/2016/03/23/npm_left_pad_chaos

What are your thoughts about the same? Do developers needs to be that much emotional?!

**Comment by sindresorhus** [comment] 2016-03-28 07:05
Duplicate of https://github.com/sindresorhus/ama/issues/367.

**Closed by sindresorhus** 2016-03-28 07:05 UTC
